package(default_visibility = ["//visibility:public"])

cc_library(
    name = "error",
    hdrs = ["error.h"],
    srcs = ["error.cpp"],
    deps = ["@com_google_absl//absl/status"],
)

cc_library(
    name = "status_macros",
    hdrs = ["status_macros.h"],
)
